### ISSUE TITLE
Get started guide

### ISSUE THREAD

**Issue by JonathanVusich** [fthevenet/openjfx-runtime-image#1]
This looks really handy, but I'm not sure how I would integrate it into an actual project. A simple demo or something would be invaluable. Thanks!

**Comment by fthevenet** [comment]
Hi,

Well this is not really something that was designed as a general purpose solution; it is simply a convenient way for me to build a custom runtime image on multiple platforms , with only the modules I need for other projects.

Of course you're welcome to fork it to include the modules you need, but now that [jpackage](https://openjdk.java.net/jeps/343) is finally available in JDK14, I suspect it might be better suited to your need.

However, if you still think what's in this project is precisely what you need and have specific questions about it, just ask.
